<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_okeAlert</name>
   <tag></tag>
   <elementGuidId>1ebaecc5-c714-4682-b96e-a7788f84a32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//android.widget.Button[@text=\'OK\']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
